In [21]:
# Naive Bayes
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv(r"C:\Users\Anish\Downloads\Social_Network_Ads.csv")

In [22]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [29]:
X = dataset.iloc[:, [1,2,3]].values             #ismei humne dependent auur indepedent variable ko alag kra h.
y = dataset.iloc[:, -1].values

In [30]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [32]:
from sklearn.preprocessing import LabelEncoder         #humne labelencoder isliyae use kia h kunki humari jo X m values h use 0and1 m krne k liye

In [33]:
le = LabelEncoder()       #yhape humne labelencoder ka object bna lia.

In [36]:
X[:,0]=le.fit_transform(X[:,0])           # yhape humne fit transform isliyae use kia kyunki humne 0 and 1 ki form m laani thi first column 

In [37]:
X[:,0]

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,

In [38]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [39]:
len(X_train)

300

In [40]:
len(X_test)

100

In [41]:
# abh hume naive bayes ka use krna h 
# naive bayes k andr multiple clases h jo class hum use krne vale h vo gaussian classifier

from sklearn.naive_bayes import GaussianNB

In [44]:
#abh hum gaussian bayes ka object bna lete h .

model = GaussianNB()

In [45]:
#abh hume model ko train krna h.
model.fit(X_train,y_train)

GaussianNB()

In [46]:
#abh model train ho chuka h abh puri tarah se ready h prediction krne k liye.
model.predict(X_test)        #purchased = 1 and not purchased = 0.

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [47]:
X_test                  # 1 -> male and 0 -> female.

array([[1, 30, 87000],
       [0, 38, 50000],
       [1, 35, 75000],
       [0, 30, 79000],
       [0, 35, 50000],
       [1, 27, 20000],
       [0, 31, 15000],
       [1, 36, 144000],
       [0, 18, 68000],
       [1, 47, 43000],
       [1, 30, 49000],
       [0, 28, 55000],
       [1, 37, 55000],
       [1, 39, 77000],
       [1, 20, 86000],
       [0, 32, 117000],
       [1, 37, 77000],
       [1, 19, 85000],
       [0, 55, 130000],
       [1, 35, 22000],
       [0, 35, 47000],
       [0, 47, 144000],
       [0, 41, 51000],
       [1, 47, 105000],
       [0, 23, 28000],
       [0, 49, 141000],
       [0, 28, 87000],
       [1, 29, 80000],
       [0, 37, 62000],
       [0, 32, 86000],
       [1, 21, 88000],
       [1, 37, 79000],
       [1, 57, 60000],
       [1, 37, 53000],
       [1, 24, 58000],
       [1, 18, 52000],
       [1, 22, 81000],
       [0, 34, 43000],
       [0, 31, 34000],
       [0, 49, 36000],
       [1, 27, 88000],
       [1, 41, 52000],
       [0, 27, 84000],
     

In [48]:
#abh hum score test kr lete h.
model.score(X_test,y_test)

0.9